# Generated by Django 2.0.13 on 2019-05-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapons_name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('length', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('barrel_length', models.PositiveIntegerField()),
                ('mass', models.PositiveIntegerField()),
                ('caliber', models.PositiveIntegerField()),
                ('method_manufacture_barrel', models.TextField()),
                ('number_rifling', models.PositiveIntegerField()),
                ('direction_rifling', models.TextField()),
                ('width_fields_rifling', models.PositiveIntegerField()),
                ('angle_rifling', models.PositiveIntegerField()),
                ('gas_outlet', models.TextField()),
                ('strikers_diameter', models.PositiveIntegerField()),
                ('width_hook_extractor', models.PositiveIntegerField()),
                ('angle_between_hook_reflector', models.PositiveIntegerField()),
                ('chamber_shape', models.PositiveIntegerField()),
                ('chamber_length', models.PositiveIntegerField()),
                ('trace_pattern_sleev', models.TextField()),
                ('sleeves_reflection', models.TextField()),
                ('automation_principle', models.TextField()),
                ('locking_mech', models.TextField()),
                ('trigger_mech', models.TextField()),
                ('safety_catch', models.TextField()),
                ('used_ammo', models.TextField()),
                ('magazine', models.TextField()),
                ('magazines_capacity', models.PositiveIntegerField()),
                ('marking_designation_description', models.TextField()),
                ('location_details', models.TextField()),
                ('disassembly_procedure', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
    ]
