# Generated by Django 2.0.13 on 2019-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='liner_removal_mech',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
