# Generated by Django 2.0.13 on 2019-05-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weapon_liner_removal_mech'),
    ]

    operations = [
        migrations.CreateModel(
            name='ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo_name', models.CharField(max_length=80)),
                ('ammo_producer', models.CharField(max_length=100)),
                ('ammo_length', models.IntegerField()),
                ('powder_mass', models.IntegerField()),
                ('ignition_type', models.CharField(max_length=160)),
                ('mounting_method', models.CharField(max_length=160)),
                ('shell_length', models.IntegerField()),
                ('diameter_dults', models.IntegerField()),
                ('diameter_case_slope', models.IntegerField()),
                ('case_diameter_bottom', models.IntegerField()),
                ('bottom_diameter', models.IntegerField()),
                ('flange_diameter', models.IntegerField()),
                ('form', models.TextField()),
                ('material_color', models.CharField(max_length=80)),
                ('capsule_type', models.CharField(max_length=80)),
                ('capsule_material_color', models.CharField(max_length=80)),
                ('diameter', models.IntegerField()),
                ('head_part_form', models.CharField(max_length=80)),
                ('bullet_length', models.IntegerField()),
                ('diameter_head_part', models.IntegerField()),
                ('bullet_mass', models.IntegerField()),
                ('bullet_type', models.CharField(max_length=80)),
                ('markings', models.TextField()),
            ],
        ),
    ]
