# Generated by Django 2.0.13 on 2019-05-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ammo'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_title', models.CharField(max_length=100)),
            ],
        ),
    ]
