# Generated by Django 2.0.13 on 2019-06-14 20:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_special_means_type_of_sm'),
    ]

    operations = [
        migrations.CreateModel(
            name='helmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet_title', models.CharField(max_length=100)),
                ('helmet_material', models.CharField(max_length=200)),
                ('helmet_hight', models.PositiveIntegerField()),
                ('helmet_width', models.PositiveIntegerField()),
                ('helmet_total_protection_area', models.PositiveIntegerField()),
                ('helmet_size', models.CharField(max_length=100)),
                ('helmet_mass', models.PositiveIntegerField()),
                ('helmet_protection_class', models.CharField(max_length=80)),
                ('helmet_image', models.ImageField(upload_to='')),
                ('helmet_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_type', models.IntegerField(choices=[(0, 'Собака'), (1, 'Лощадь')], default=0)),
                ('kind', models.CharField(max_length=100)),
                ('average_hight', models.PositiveIntegerField()),
                ('average_lenght', models.PositiveIntegerField(blank=True)),
                ('using_for', models.TextField()),
                ('jaws_strength', models.PositiveIntegerField()),
                ('animals_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest_title', models.CharField(max_length=80)),
                ('body_material', models.CharField(max_length=80)),
                ('vests_color', models.CharField(max_length=100)),
                ('vests_length', models.PositiveIntegerField()),
                ('vests_width', models.PositiveIntegerField()),
                ('vest_mass', models.CharField(max_length=20)),
                ('vest_size', models.CharField(max_length=40)),
                ('materials', models.CharField(max_length=200)),
                ('protection_area', models.PositiveIntegerField()),
                ('total_protection_area', models.PositiveIntegerField()),
                ('material_of_armor_elements', models.CharField(max_length=200)),
                ('protection_class', models.CharField(max_length=40)),
                ('cloth', models.CharField(max_length=200)),
                ('wearing_type', models.CharField(max_length=100)),
                ('vest_image', models.ImageField(upload_to='')),
                ('vest_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='marking_image',
            field=models.ImageField(blank=True, upload_to=core.models.image_folder),
        ),
        migrations.AddField(
            model_name='weapon',
            name='trace_pattern_sleev_image',
            field=models.ImageField(blank=True, upload_to=core.models.image_folder),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapons_photo',
            field=models.ImageField(blank=True, upload_to=core.models.image_folder),
        ),
    ]
