# Generated by Django 2.0.13 on 2019-06-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190625_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие'},
        ),
    ]
