# Generated by Django 2.0.13 on 2019-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190704_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammo',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='helmet',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='mobility_limiting_means',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='service_animals',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='special_gas_facilities',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='special_sticks',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='stun_devices',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vest',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
