# Generated by Django 2.0.13 on 2019-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190713_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(),
        ),
    ]
