# Generated by Django 2.0.13 on 2019-09-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190916_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ammo',
            old_name='slug',
            new_name='ammo_slug',
        ),
        migrations.RenameField(
            model_name='helmet',
            old_name='slug',
            new_name='helmet_slug',
        ),
        migrations.RenameField(
            model_name='mobility_limiting_means',
            old_name='slug',
            new_name='mlm_slug',
        ),
        migrations.RenameField(
            model_name='service_animals',
            old_name='slug',
            new_name='sa_slug',
        ),
        migrations.RenameField(
            model_name='special_gas_facilities',
            old_name='slug',
            new_name='sgf_slug',
        ),
        migrations.RenameField(
            model_name='special_sticks',
            old_name='slug',
            new_name='ss_slug',
        ),
        migrations.RenameField(
            model_name='stun_devices',
            old_name='slug',
            new_name='sd_slug',
        ),
        migrations.RenameField(
            model_name='vest',
            old_name='slug',
            new_name='vest_slug',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='slug',
            new_name='weapon_slug',
        ),
        migrations.AlterField(
            model_name='service_animals',
            name='animals_type',
            field=models.IntegerField(choices=[(0, 'Собака'), (1, 'Лошадь')], default=0, verbose_name='Вид'),
        ),
    ]
