# Generated by Django 2.0.13 on 2019-09-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_air_weapon_gas_weapon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='air_weapon',
            options={'verbose_name': 'Пневматическое ружие', 'verbose_name_plural': 'Пневматическое ружие'},
        ),
    ]
